### ISSUE TITLE
instant crash while loading a defensive battle

### ISSUE THREAD

**Issue by MendorTheKreet** [cortex-command-community/Cortex-Command-Community-Project-Data#130]
Basically starting a defensive battle in singleplayer instantly crashes the game, while having more than enough RAM for the game to run  normally
maybe it's an anti lag code conflict, or the game not having enough RAM (while not having any RAM restrictions on anything), or maybe a corrupted save ?

**Comment by garethyr** [comment]
Try grabbing this version, it's got some bug fixes, maybe it'll help ya:
https://dl.orangedox.com/CCCP-Pre-Pre-Release-4.1.0

If it solves things, please lemme know.
