### ISSUE TITLE
Attempt larger maps, preferably without wrapping

### ISSUE THREAD

**Issue by garethyr** [cortex-command-community/Cortex-Command-Community-Project-Data#14]
As part of an effort to make the game more strategic in general, we need bigger maps, probably without wrapping.
Extended versions of current maps are perfectly fine as long as they look and feel good.

**Comment by Pockets-byte** [comment]
working on this with https://github.com/cortex-command-community/Cortex-Command-Community-Project-Data/pull/151

**Comment by Causeless** [comment]
Pre-5.2 + Decision Day has shown that this is possible and now there's now little-to-no performance upper-limit of map size. Would suggest closing as completed.
