### ISSUE TITLE
Make doors significantly tougher

### ISSUE THREAD

**Issue by garethyr** [cortex-command-community/Cortex-Command-Community-Project-Data#15]
Doors are mostly cardboard. Given that they're defending the entrances to heavily guarded futuristic military-like installations, they should be tough as hell.

All doors should be made of a tougher material and probably have more wounds. Ideally, specialist equipment would be needed to breach these, or some serious explosives.

**Comment by MaximDude** [comment]
Also, drawing of the material layer of door objects that gave actors the ability to stand on them without spazzing out appears to be broken and needs fixing.

It mostly fails when the door is in open state, but it also appears to fail randomly when the door is in closed state, giving enemy actors a chance to glitch through it.

See `ADoor.DrawDoorMaterial` and all that is related to it.

**Comment by Envy-glitch** [comment]
It would probably be a good thing to make AI recognize that they need to use proper equipment on them in the future.

**Comment by garethyr** [comment]
Looks like we never marked this as completed, even though both the data and source work for this has been done. Oops.
