### ISSUE TITLE
Make diggers better

### ISSUE THREAD

**Issue by garethyr** [cortex-command-community/Cortex-Command-Community-Project-Data#16]
The base game diggers are, currently, a mess. Heavy digger is too weak, medium digger is too strong, etc.
While it's early to be doing rebalancing, this is a relatively isolated piece of rebalancing and will work well with the other content changes here.

The general consensus on digger strength is:
* Light digger should be able to get through sand, scrap and gold if you're lucky enough to get there
* Medium digger should chew through dirt but have a tough time with concrete and rock and be useless against metal
* Heavy digger should possibly be renamed/replaced with something more befitting its function - slowly but surely breaching bases
* Turbo digger and pulse digger can probably be removed or if not, I guess they stay much as they are now with around the same capability of medium digger
* Nanolyzer should probably go, or be unable to handle/slow at handling concrete and metal.

Diggers should also be less damaging against people, I believe there's been an effort to make most of their particles not hit mos, which might suffice.

**Comment by fourZK** [comment]
I've done *exactly* these changes already; uninteresting faction diggers oughta be revised / removed. Pulse digger is out, Turbo digger can stay with some touch-ups. I don't know about the Nanolyzer, imo it can stay as is, as it's not that good at digging in general.

I have made a global script to nerf digger particles, which is technically more efficient than running a nerf script on each particle, right? Other methods, like having only the tracer HitsMOs = 1 makes the damage output too ugly. Alternatively, we could redo the digger damage output altogether. I'll try out some ideas.

**Comment by Flameport** [comment]
> I've done _exactly_ these changes already; uninteresting faction diggers oughta be revised / removed. Pulse digger is out, Turbo digger can stay with some touch-ups. I don't know about the Nanolyzer, imo it can stay as is, as it's not that good at digging in general.
> 
> I have made a global script to nerf digger particles, which is technically more efficient than running a nerf script on each particle, right? Other methods, like having only the tracer HitsMOs = 1 makes the damage output too ugly. Alternatively, we could redo the digger damage output altogether. I'll try out some ideas.

well i think the nanolyser is like more of a door than a  digger it makes it easier for  diggers to dig like with a nanolyser your medium digger can dig metal. on the pulse digger i think it could stay because its like a light or medium digger but it digs faster because it kinda "pulses" repeatily but its only for the coalition so its balenced
