### ISSUE TITLE
Hardcoded attachments like legs might need lua access too

### ISSUE THREAD

**Issue by pawnishoovy** [cortex-command-community/Cortex-Command-Community-Project-Data#22]
**Is your feature request related to a problem? Please describe.**
Things like arms, legs, feet, hands, heads might need to be accessible to lua like normal attachments (armor most often) now are thanks to the work done. This allows for more swanky things to be done in general, for example regenerating limbs or swapping them out (androids?).

**Describe the solution you'd like**
Allow lua to add and remove hardcoded attachments like legs and arms. Those two should come first (AHuman legs, arms that is) but eventually all of them being available would be good. 

**Describe alternatives you've considered**

Ultimately we can already manipulate a lot of base level stuff like wounds or whatever even on hardcoded attachments. Allowing full swapping of such things would mainly serve to change the sprite (and resulting hitboxes). So, instead of actually swapping one leg out for another, maybe allow swapping spritepaths realtime? This would also add a lot of utility to non attachment related stuff, and possibly serve as one solution to every sort of hardcoded attachment.

**Comment by MaximDude** [comment]
Isn't relevant to Data repository. Reopen in [Source repository](https://github.com/cortex-command-community/Cortex-Command-Community-Project-Source/issues).
