### ISSUE TITLE
Grenades reset their exploding timer if picked up

### ISSUE THREAD

**Issue by pawnishoovy** [cortex-command-community/Cortex-Command-Community-Project-Data#23]
**Describe the bug**
Picking up an activated grenade will reset its timer, making it possible to throw one back and forth without it ever exploding.

**To Reproduce**
Have two actors
Throw a grenade from one to the other
Pick up the activated grenade and throw it back
Repeat
Observe as it never explodes

**Expected behavior**
Grenades should not reset their timer and explode at the correct time from first activation even if picked up.

**Comment by MaximDude** [comment]
Isn't relevant to Data repository. Reopen in [Source repository](https://github.com/cortex-command-community/Cortex-Command-Community-Project-Source/issues).
