### ISSUE TITLE
actor.StepFrame for detecting footsteps

### ISSUE THREAD

**Issue by pawnishoovy** [cortex-command-community/Cortex-Command-Community-Project-Data#24]
**Is your feature request related to a problem? Please describe.**
It's impossible to detect when a footstep occurs (i.e. when a footstep sound plays), which makes it close to impossible to add custom sounds that occur simultaneously with footsteps.

**Describe the solution you'd like**
FiredFrame, but for footsteps. True on the frame one occurs, false otherwise.

EDIT: Add a new cpp sound, "StepSound" that plays similarly to StrideSound, but only when on contact with terrain.

Two variants:
StepSoundSoft: when the material strength of the terrain is less than the material strength of the foot. (dirt etc.)
StepSoundHard: vice versa. (higher _or_ equal)

In addition, the amplitude of the steps probably shouldn't be as loud as any sound (to avoid sound 'pollution'), possibly decreasing at a higher rate when screen-to-source distance increases.

**Comment by fourZK** [comment]
I think we should instead make StrideSound take terrain to account, or even make a brand new StepSound to serve the purpose. Maybe two, even: one for "soft" and one for "hard" terrain, in relation to the material strength of the foot, perhaps?

**Comment by MaximDude** [comment]
Isn't relevant to Data repository. Reopen in [Source repository](https://github.com/cortex-command-community/Cortex-Command-Community-Project-Source/issues).
