### ISSUE TITLE
Metagame Crashing

### ISSUE THREAD

**Issue by JazzYourFavPagan** [cortex-command-community/Cortex-Command-Community-Project-Data#27]
**Describe the bug**
Game Crash, no "RTE aborted" tab, as far as I have seen.

**To Reproduce**
1. Choose any faction in Metagame
2. Acquire a base
3. Provide fortification budget with Auto ON
4. End Turn
5. Observe complete lack of responsiveness from game.

**Expected behavior**
I expected my base to be fortified after ending my turn.

**Screenshots**

**Additional context**

**Comment by fourZK** [comment]
This is purely because of missing faction loadouts as a result of the base refactor, rendering metagame obsolete until further faction refactors. In the time being, you'll have to create your own loadouts (see Loadouts.ini files in B33) or play something other than metagame.
