### ISSUE TITLE
Skirimish Defense Doors

### ISSUE THREAD

**Issue by Envy-glitch** [cortex-command-community/Cortex-Command-Community-Project-Data#37]
**Describe the bug**
When playing Skirimish Defense, the doors present in the map are assigned to the wrong team

**Additional context**
There is a solution on the workshop, so I can take care of it

**Comment by MaximDude** [comment]
Can't confirm, doors appear to work just fine.
Drop a video or explain the setting and what is happening in detail.

**Comment by Envy-glitch** [comment]
Made some research, it seems they get assigned to Team 2 no matter which one the player picks, which doesn't make sense, since both it isn't obvious and they should be always yours since you are never the attacker in Skirmish.

**Comment by MaximDude** [comment]
I have just double checked, but with a CPU team and with a human team.
Doors work fine. Enemy team attacks correct door, doors don't open to enemy team.

**Comment by Envy-glitch** [comment]
Recorded it, it's the newest release of course
https://youtu.be/XgUU6Q1NDY8

**Comment by MaximDude** [comment]
Ok yeah, I see.
This is because the door teams are set to 1 in the scene ini.
Just remove that property.

Might as well run through all the scenes to makes sure it's not there and remove it if it is, then make a PR.
