### ISSUE TITLE
Cannot Go Fullscreen when using a Nonnative Resolution

### ISSUE THREAD

**Issue by SirJoshi** [cortex-command-community/Cortex-Command-Community-Project-Data#42]
**Describe the bug**
You Cannot Use Fullscreen When Using a Screen Resolution Lower than Your Default

**To Reproduce**
1. Have a Laptop That Uses a 1920 x 1080 Display
2. Set Game Resolution to 1600 x 900
3. Press Alt+Enter
4. Game will Only Cycle Between 1x and 2x

**Expected behavior**
Game Goes Full Screen

**Comment by MaximDude** [comment]
Native fullscreen mode has been removed and borderless fullscreen window is used instead.
To use native resolution set it manually in the settings. For 2X borderless set resolution to /2 of your native and multiplier to 2.
Cycling between multipliers with a resolution setting higher than /2 of native will prompt a warning message explaining why multipliers can't be cycled.
Please read the changelog.

If you're running an older version, do not open issues about it here unless the issue exists in the latest version.
