### ISSUE TITLE
Merge Bunker Breach and Siege into one Activity

### ISSUE THREAD

**Issue by fourZK** [cortex-command-community/Cortex-Command-Community-Project-Data#58]
If I understood correctly, Bunker Breach and Siege are attack and defense counterparts of more or less the same Activity. In addition to one or both of them being allegedly bugged (possibly because of unclear attacking and defending teams on the Scene side, causing the match to break from the start), they might as well be combined into one Activity where the teams are clearly listed as attacking and defending for the player to pick. This should also allow for PvP matches!

A sort of failsafe solution could also be that the Activity automatically sets the teams of unit presets present in the Scene to the defending team.

**Comment by garethyr** [comment]
I'm totally in favour of combining them and letting the player pick whether to be attacker or defender. You'll have to rewrite it a fair deal though, e.g. making sure no ai spawns happen for player controlled teams, etc.
