### ISSUE TITLE
Nucleo gun can crash game

### ISSUE THREAD

**Issue by tomflenniken** [cortex-command-community/Cortex-Command-Community-Project-Data#68]
**Describe the bug**
I've seen regular crashes when using Techion but not in a predictable fashion. I believe the issue to be with the nucleo gun.

**To Reproduce**
1. Hit an enemy with the nucleo (don't kill it?)
2. Reload
3. Fire a shot
4. Game crashes

**Expected behavior**
The game shouldn't crash.

**Screenshots**
The game crashes abruptly, no screenshot or abortscreen is available. Console log is empty.

**Additional context**
I feel like there needs to be a crash log captured for situations like this because it's very challenging to identify the specific cause of a crash.

**Comment by garethyr** [comment]
This has been fixed by 4zK in the pre3 data. Thanks for reporting it though.

**Comment by tomflenniken** [comment]
Yeah I realized after the fact that I should've validated against the current development version, so I've independently validated it isn't abruptly crashing any more.

**Comment by garethyr** [comment]
All good, it's easy to not think about it beforehand :)
