### ISSUE TITLE
Getting the error that a music file was not found in the metagame

### ISSUE THREAD

**Issue by MyNameIsTrez** [cortex-command-community/Cortex-Command-Community-Project-Data#74]
**Screenshots**
![image](https://user-images.githubusercontent.com/32989873/103154898-464ebb80-479b-11eb-9bcd-c1e546c7d2e4.png)

**Comment by MyNameIsTrez** [comment]
This has been moved to issue #86.

**Comment by garethyr** [comment]
This is the same bug in https://github.com/cortex-command-community/Cortex-Command-Community-Project-Source/issues/255 and fixed in the corresponding PR
