### ISSUE TITLE
Metagame MetaFight.lua error which prevents further progression

### ISSUE THREAD

**Issue by MyNameIsTrez** [cortex-command-community/Cortex-Command-Community-Project-Data#76]
**Describe the bug**
When this error occurred I was instantly kicked out of the fight that was in progress, but the game didn't crash. When the "Start!" button was hit again by me the game tried to start the fight again, only for me to be kicked out again, so the metagame is stuck.

**Screenshots**
![error](https://user-images.githubusercontent.com/32989873/103155775-ff64c400-47a2-11eb-9696-366b240177f1.png)

**Comment by fourZK** [comment]
I'm assuming this NOPLAYER enum refers to -1. I wonder what ever happened to it. It's technically an easy fix, but maybe it's worth checking out in the source first.

**Comment by garethyr** [comment]
Looks like something @MaximDude broke back in July and no one noticed 😮 
You'll want to change it to `Activity.NOTEAM`
