### ISSUE TITLE
Shovel - Failure to fill sandbag loses all stored dirt

### ISSUE THREAD

**Issue by traunts** [cortex-command-community/Cortex-Command-Community-Project-Data#85]
**Describe the bug**
When the `Fill Sandbag` pie slice is used with the shovel while having collected less than 10 units of sand, it will fail to produce a sandbag as expected but still remove all units.

**To Reproduce**
1. Equip an actor with Ronin Shovel
2. Dig up < 10 units of sand
3. Attempt to `Fill Sandbag` from pie menu
4. Sand held is reset, shovel displays defalt ammo capacity of `infinite`

**Expected behavior**
Presumably a slight lua mistake, shovel should only remove units if a sandbag is successfully created

**Comment by traunts** [comment]
On closer inspection, this seems to be because the pie slice isn't disabled when below 10 like it should be, pictured here: 
![image](https://user-images.githubusercontent.com/73866773/104556623-d774cc00-568f-11eb-9d14-f6f30af299dc.png)

**Comment by traunts** [comment]
And it's presumably removed because this line that deletes it isn't captured in the statement that checks if there's enough resource to create a new sandbag:
![image](https://user-images.githubusercontent.com/73866773/104556769-10ad3c00-5690-11eb-9179-337a9f627838.png)

**Comment by fourZK** [comment]
That's odd, like traunts mentioned - the slice shouldn't be available unless the resource conditions are met. I'll add an extra failsafe step for this.
