### ISSUE TITLE
AimRangeUpperLimit and AimRangeLowerLimit not respected in multiple places

### ISSUE THREAD

**Issue by Armokorguest** [cortex-command-community/Cortex-Command-Community-Project-Data#88]
There are multiple places, primarily in the lua AI code, where AimRangeUpperLimit and AimRangeLowerLimit are not respected, and instead it only uses the old AimRange. This was presumably not discovered because they are not used in vanilla and so there's no ingame way they come up without mods.

Specific spots it comes up is in CrabBeaviors.lua on lines 92 and 93, and in HumanBehaviors.lua on lines 301 and 302 and 1345. There might be others.

**Comment by garethyr** [comment]
Please reconcile this with #87 and close one of these issues.
