### ISSUE TITLE
Actor heads colide with dropship, both by pickup and drop

### ISSUE THREAD

**Issue by GotchaCC** [cortex-command-community/Cortex-Command-Community-Project-Data#89]
Seems like, aside from actor heads not being able to get inside dropships (which is a well-known issue by now), there's now also a new problem in pre3 where actor heads briefly get stuck in dropships when dropped. 
So the heads-dropship colission problem has worsened.

**Comment by garethyr** [comment]
Thanks for the issue report :) It's been solved already, will be gone in pre3.1.
